server:
 port: 8580

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb
    username: root
    password: Shivam@12

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  cloud:
    gateway:

      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              #allowCredentials: true
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS

      routes:
        - id: service_cart
          uri: http://localhost:7075
          predicates:
            - Path=/cart/**
          filters:
            - AuthenticateFilterFactory
        - id: whishlistms
          uri: http://localhost:8080
          predicates:
            - Path=/**
          filters:
            - AuthenticateFilterFactory
  application:
    name: userms

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:9000/eureka"
